# Generated by Django 4.0.3 on 2022-04-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='שם')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='תאריך לידה')),
                ('age', models.IntegerField(default=0, verbose_name='גיל')),
                ('gender', models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=6, verbose_name='מגדר')),
                ('image', models.ImageField(blank=True, default='media/generic_img.png', upload_to='mediaCats/', verbose_name='הוסף תמונה')),
                ('description', models.TextField(max_length=360, verbose_name='תיאור החתול/ה')),
                ('location', models.CharField(choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ')], max_length=20, verbose_name='מיקום')),
                ('acceptance_date', models.DateField(default=datetime.date.today, verbose_name='תאריך קבלה לעמותה')),
                ('number_of_days_in_the_association', models.IntegerField(default=1, verbose_name='מספר ימים בעמותה')),
                ('story', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיפור החתול/ה')),
                ('notebook', models.BooleanField(default=False, verbose_name='פנקס חיסונים')),
                ('square_vaccine', models.BooleanField(default=False, verbose_name='חיסון מרובע')),
                ('ticks_fleas_treatment', models.DateField(default=None, verbose_name='טיפול קרציות ופרעושים')),
                ('sterilization', models.DateField(default=None, verbose_name='סירוס/ עיקור')),
                ('next_treatment', models.DateField(default=None, verbose_name='תאריך הטיפול הבא')),
                ('next_treatment_comments', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות לטיפול הבא')),
                ('died', models.BooleanField(default=False, verbose_name='נפטר/ה')),
                ('death_reason', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת פטירה')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='תאריך פטירה')),
                ('adopter_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ת.ז של מאמץ')),
                ('vaccine_book_url', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לפנקס חיסונים')),
                ('sterilization_approval_link', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לאישור סירוס/ עיקור')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chip_number', models.IntegerField(unique=True, verbose_name='מספר שבב')),
                ('name', models.CharField(max_length=255, verbose_name='שם')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='תאריך לידה')),
                ('age', models.IntegerField(default=0, verbose_name='גיל')),
                ('gender', models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=6, verbose_name='מין')),
                ('image', models.ImageField(blank=True, default='media/generic_img.png', upload_to='mediaDogs/', verbose_name='הוסף תמונה')),
                ('size', models.CharField(max_length=255, verbose_name='גודל (קטן/ בינוני/ גדול')),
                ('color', models.CharField(max_length=255, verbose_name='צבע')),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='תיאור הכלב')),
                ('location', models.CharField(choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ')], max_length=20, verbose_name='מיקום הכלב')),
                ('behaviour_description', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='תיאור התנהגותי')),
                ('acceptance_date', models.DateField(default=datetime.date.today, verbose_name='תאריך קבלה לעמותה')),
                ('number_of_days_in_the_association', models.IntegerField(default=1, verbose_name='מספר ימים בעמותה')),
                ('story', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיפור הכלב')),
                ('clinic', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='מרפאה וטרינרית')),
                ('notebook', models.BooleanField(default=False, verbose_name='יש פנקס חיסונים?')),
                ('rabbies_vaccine', models.DateField(blank=True, null=True, verbose_name='חיסון כלבת')),
                ('hexagonal_vaccine', models.DateField(blank=True, null=True, verbose_name='חיסון משושה')),
                ('nonagonal_vaccine', models.DateField(blank=True, null=True, verbose_name='חיסון מתושע')),
                ('ocagonal_vaccine1', models.DateField(blank=True, null=True, verbose_name='חיסון מתומן 1')),
                ('ocagonal_vaccine2', models.DateField(blank=True, null=True, verbose_name='חיסון מתומן 2')),
                ('ocagonal_vaccine3', models.DateField(blank=True, null=True, verbose_name='חיסון מתומן 3')),
                ('worming', models.DateField(blank=True, null=True, verbose_name='תילוע')),
                ('simparica', models.DateField(blank=True, null=True, verbose_name='סימפריקה')),
                ('medical_comments', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות רפואיות')),
                ('sterilization', models.DateField(blank=True, null=True, verbose_name='סירוס/ עיקור')),
                ('next_treatment', models.DateField(blank=True, null=True, verbose_name='תאריך הטיפול הבא')),
                ('next_treatment_comments', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות לטיפול הבא')),
                ('died', models.BooleanField(default=False, verbose_name='נפטר/ה')),
                ('death_reason', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת פטירה')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='תאריך המוות')),
                ('adopter_name', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='שם המאמצ/ת')),
                ('adoption_date', models.DateField(blank=True, null=True, verbose_name='תאריך אימוץ')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='תאריך החזרה')),
                ('reason_of_return', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת ההחזרה')),
                ('vaccine_book_url', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לפנקס חיסונים')),
                ('sterilization_approval_link', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לאישור סירוס/ עיקור')),
                ('rabbies_vaccine_aproval_link', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לאישור חיסון כלבת')),
                ('giveaway_forms', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='מסמך החזרה')),
                ('waiver_forms', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='מסמך העברה')),
                ('returner_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='תעודת זהות של מחזיר הכלב/ה')),
            ],
        ),
    ]
