# Generated by Django 4.0.3 on 2022-04-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
    ]
