# Generated by Django 4.0.3 on 2022-04-22 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='number_of_days_in_the_association',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sterilization_approval_link',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='next_treatment',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='number_of_days_in_the_association',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='rabbies_vaccine_aproval_link',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='sterilization_approval_link',
        ),
        migrations.AddField(
            model_name='cat',
            name='sterilization_approval',
            field=models.ImageField(blank=True, default=None, upload_to='mediaCats/', verbose_name='אישור סירוס/עיקור'),
        ),
        migrations.AddField(
            model_name='dog',
            name='adopter_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ת.ז. של המאמצ/ת'),
        ),
        migrations.AddField(
            model_name='dog',
            name='exit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='תאריך יציאה מעמותה'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_hexagonal',
            field=models.DateField(blank=True, null=True, verbose_name='משושה - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_rabies',
            field=models.DateField(blank=True, null=True, verbose_name='כלבת - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_simparica',
            field=models.DateField(blank=True, null=True, verbose_name='סימפריקה - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_worming',
            field=models.DateField(blank=True, null=True, verbose_name='תילוע - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='rabies_vaccine_approval',
            field=models.ImageField(default=None, upload_to='mediaDogs/', verbose_name='אישור חיסון כלבת'),
        ),
        migrations.AddField(
            model_name='dog',
            name='sterilization_approval',
            field=models.ImageField(blank=True, default=None, upload_to='mediaDogs/', verbose_name='אישור סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='adopter_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ת.ז של המאמצ/ת'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=6, verbose_name='מין'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.CharField(choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], max_length=20, verbose_name='מיקום'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sterilization',
            field=models.DateField(default=None, verbose_name='סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='chip_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='מספר שבב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך הפטירה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], max_length=20, verbose_name='מיקום הכלב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='returner_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ת.ז. של מחזיר הכלב/ה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('Small', 'קטן'), ('Medium', 'בינוני'), ('Big', 'גדול')], max_length=255, verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sterilization',
            field=models.DateField(blank=True, null=True, verbose_name='סירוס/עיקור'),
        ),
    ]
