# Generated by Django 2.2 on 2022-05-11 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_ID', models.IntegerField(default=None, unique=True, verbose_name='ת"ז')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='שם המאמצ/ת')),
                ('ID_link', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לת"ז')),
                ('adopter_city', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='עיר מגורים')),
                ('adopter_street', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='רחוב')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='מספר טלפון')),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='כתובת מייל')),
                ('activity_status', models.CharField(choices=[('ACTIVE ADOPTION', 'אימץ'), ('RETURNED', 'החזיר')], default='אימץ', max_length=20, verbose_name='סטטוס פעילות')),
                ('black_listed', models.BooleanField(default=False, verbose_name='רשימה שחורה')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_owner', models.CharField(max_length=255, verbose_name='שם מטפלת ')),
                ('status', models.CharField(max_length=255, verbose_name='')),
                ('comments', models.CharField(max_length=255, verbose_name=' ')),
                ('full_name', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('age', models.IntegerField(editable=False, verbose_name=' ')),
                ('city', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('phone_num', models.CharField(editable=False, max_length=255, verbose_name='')),
                ('mail', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('maritalStatus', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('numChildren', models.IntegerField(editable=False, verbose_name=' ')),
                ('otherPets', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('experience', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('dog_name', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('allergies', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('own_apartment', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('rent_agreed', models.CharField(editable=False, max_length=255, verbose_name='')),
                ('residenceType', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('fence', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('dogPlace', models.CharField(editable=False, max_length=255, verbose_name='')),
                ('dogSize', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('response_comments', models.CharField(editable=False, max_length=255, verbose_name=' ')),
                ('response_date', models.DateTimeField()),
                ('QID', models.IntegerField(editable=False, unique=True, verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='notebook',
            new_name='vaccination_book',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='rabbies_vaccine',
            new_name='rabies_vaccine',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='adopter_id',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='next_treatment',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='next_treatment_comments',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='number_of_days_in_the_association',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sterilization_approval_link',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='vaccine_book_url',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adopter_name',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adoption_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='giveaway_forms',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='next_treatment',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='next_treatment_comments',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='nonagonal_vaccine',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='number_of_days_in_the_association',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='ocagonal_vaccine1',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='ocagonal_vaccine2',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='ocagonal_vaccine3',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='rabbies_vaccine_aproval_link',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='reason_of_return',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='returner_id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='simparica',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='sterilization_approval_link',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='vaccine_book_url',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='waiver_forms',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='worming',
        ),
        migrations.AddField(
            model_name='cat',
            name='animal_type',
            field=models.CharField(default='חתול', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='cat',
            name='clinic',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='מרפאה וטרינרית'),
        ),
        migrations.AddField(
            model_name='cat',
            name='medical_comments',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות רפואיות'),
        ),
        migrations.AddField(
            model_name='cat',
            name='next_ticks_fleas_treatment',
            field=models.DateField(blank=True, null=True, verbose_name='קרציות ופרעושים - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='cat',
            name='physical_description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='תיאור חיצוני'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sterilization_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaCats/', verbose_name='אישור סירוס/עיקור'),
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccination_book_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaCats/', verbose_name='קישור לפנקס חיסונים'),
        ),
        migrations.AddField(
            model_name='cat',
            name='worming_1',
            field=models.DateField(blank=True, null=True, verbose_name='תילוע 1'),
        ),
        migrations.AddField(
            model_name='cat',
            name='worming_2',
            field=models.DateField(blank=True, null=True, verbose_name='תילוע 2'),
        ),
        migrations.AddField(
            model_name='dog',
            name='animal_type',
            field=models.CharField(default='כלב', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='dog',
            name='medical_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='קישור לתיק רפואי'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_ticks_fleas_treatment',
            field=models.DateField(blank=True, null=True, verbose_name='קרציות ופרעושים - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_hexagonal',
            field=models.DateField(blank=True, null=True, verbose_name='משושה - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='next_treatment_rabies',
            field=models.DateField(blank=True, null=True, verbose_name='כלבת - תאריך הטיפול הבא'),
        ),
        migrations.AddField(
            model_name='dog',
            name='physical_description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='תיאור חיצוני'),
        ),
        migrations.AddField(
            model_name='dog',
            name='rabies_vaccine_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='אישור חיסון כלבת'),
        ),
        migrations.AddField(
            model_name='dog',
            name='sterilization_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='אישור סירוס/עיקור'),
        ),
        migrations.AddField(
            model_name='dog',
            name='ticks_fleas_treatment',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='טיפול קרציות ופרעושים'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_book',
            field=models.BooleanField(default=False, verbose_name='פנקס חיסונים'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_book_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='קישור לפנקס חיסונים'),
        ),
        migrations.AddField(
            model_name='dog',
            name='worming_1',
            field=models.DateField(blank=True, null=True, verbose_name='תילוע 1'),
        ),
        migrations.AddField(
            model_name='dog',
            name='worming_2',
            field=models.DateField(blank=True, null=True, verbose_name='תילוע 2'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='acceptance_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך כניסה לעמותה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='death_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='תאריך הפטירה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='death_reason',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת הפטירה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=6, verbose_name='מין'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', null=True, upload_to='mediaCats/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.CharField(blank=True, choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], default='עמותה', max_length=20, null=True, verbose_name='מיקום'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sterilization',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='story',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיפור רקע'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='ticks_fleas_treatment',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='טיפול קרציות ופרעושים'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='acceptance_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך קבלה לעמותה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='chip_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='מספר שבב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך הפטירה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='death_reason',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת הפטירה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=255, verbose_name='מין'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', null=True, upload_to='mediaDogs/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], default='עמותה', max_length=255, null=True, verbose_name='מיקום הכלב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'קטן'), ('Medium', 'בינוני'), ('Big', 'גדול')], default=None, max_length=255, null=True, verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sterilization',
            field=models.DateField(blank=True, null=True, verbose_name='סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='story',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיפור רקע'),
        ),
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(default=datetime.date.today, verbose_name='תאריך האימוץ')),
                ('method_of_payment', models.CharField(default=None, max_length=255, verbose_name='שיטת התשלום')),
                ('receipt_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='מספר חשבונית')),
                ('adoption_form_link', models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='קישור למסמך האימוץ')),
                ('adoption_comments', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות האימוץ')),
                ('last_followup_call', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='שיחת מעקב אחרונה')),
                ('next_followup_call', models.DateField(default=datetime.date.today, verbose_name='תאריך שיחת מעקב הבאה')),
                ('adoption_volunteer', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='גורם מטפל באימוץ')),
                ('returned', models.BooleanField(default=False, verbose_name='החזרה')),
                ('return_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך החזרה')),
                ('return_reason', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת החזרה')),
                ('return_volunteer', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='גורם מטפל בהחזרה')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Adopter', verbose_name='שם המאמצ/ת')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Dog', verbose_name='שם הכלב')),
            ],
        ),
        migrations.CreateModel(
            name='CatAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(default=datetime.date.today, verbose_name='תאריך האימוץ')),
                ('method_of_payment', models.CharField(default=None, max_length=255, null=True, verbose_name='שיטת התשלום')),
                ('receipt_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='מספר חשבונית')),
                ('adoption_form_link', models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='קישור למסמך האימוץ')),
                ('adoption_comments', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות האימוץ')),
                ('last_followup_call', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='שיחת מעקב אחרונה')),
                ('next_followup_call', models.DateField(default=datetime.date.today, verbose_name='תאריך שיחת מעקב הבאה')),
                ('adoption_volunteer', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='גורם מטפל באימוץ')),
                ('returned', models.BooleanField(default=False, verbose_name='החזרה')),
                ('return_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך החזרה')),
                ('return_reason', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת החזרה')),
                ('return_volunteer', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='גורם מטפל בהחזרה')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Adopter', verbose_name='שם המאמצ/ת')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Cat', verbose_name='שם החתול')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='adopter_relation_cat',
            field=models.ManyToManyField(related_name='adoptions_cat', through='shelter.CatAdoption', to='shelter.Adopter'),
        ),
        migrations.AddField(
            model_name='dog',
            name='adopter_relation_dog',
            field=models.ManyToManyField(related_name='adoptions_dog', through='shelter.DogAdoption', to='shelter.Adopter'),
        ),
    ]
