# Generated by Django 4.0.4 on 2022-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_remove_cat_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='adopter_id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adopter_id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adopter_name',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adoption_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='giveaway_forms',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='reason_of_return',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='returner_id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='waiver_forms',
        ),
        migrations.AddField(
            model_name='dog',
            name='physical_description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='תיאור חיצוני'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_book',
            field=models.BooleanField(default=False, verbose_name='פנקס חיסונים'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', upload_to='mediaCats/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='death_reason',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת הפטירה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], max_length=255, verbose_name='מין'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', upload_to='mediaDogs/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], max_length=255, verbose_name='מיקום הכלב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='next_treatment_comments',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='הערות לטיפולים הבאים'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='story',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיפור רקע'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vaccine_book_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='קישור לפנקס חיסונים'),
        ),
    ]
