# Generated by Django 4.0.4 on 2022-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_remove_cat_adopter_id_remove_dog_adopter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='rabies_vaccine_approval',
            field=models.FileField(default=None, upload_to='mediaDogs/', verbose_name='אישור חיסון כלבת'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sterilization_approval',
            field=models.FileField(blank=True, default=None, upload_to='mediaDogs/', verbose_name='אישור סירוס/עיקור'),
        ),
    ]
