# Generated by Django 4.0.3 on 2022-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_dog_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('Small', 'קטן'), ('Medium', 'בינוני'), ('Big', 'גדול')], max_length=255, verbose_name='גודל'),
        ),
    ]
