# Generated by Django 4.0.3 on 2022-04-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_dog_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
    ]
