# Generated by Django 4.0.4 on 2022-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_dog_rabies_vaccine_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='rabies_vaccine_approval',
            field=models.FileField(blank=True, default=None, upload_to='mediaDogs/', verbose_name='אישור חיסון כלבת'),
        ),
    ]
