# Generated by Django 4.0.4 on 2022-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_alter_dog_rabies_vaccine_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', null=True, upload_to='mediaDogs/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], default=None, max_length=255, null=True, verbose_name='מיקום הכלב'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='rabies_vaccine_approval',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='אישור חיסון כלבת'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'קטן'), ('Medium', 'בינוני'), ('Big', 'גדול')], default=None, max_length=255, null=True, verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sterilization_approval',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mediaDogs/', verbose_name='אישור סירוס/עיקור'),
        ),
    ]
