# Generated by Django 4.0.4 on 2022-04-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_alter_dog_color_alter_dog_image_alter_dog_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='rabbies_vaccine',
            new_name='rabies_vaccine',
        ),
    ]
