# Generated by Django 4.0.4 on 2022-04-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_rename_rabbies_vaccine_dog_rabies_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='acceptance_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך קבלה לעמותה'),
        ),
    ]
