# Generated by Django 4.0.4 on 2022-04-22 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0008_alter_dog_acceptance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='acceptance_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='תאריך קבלה לעמותה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='death_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='תאריך פטירה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=360, null=True, verbose_name='תיאור החתול/ה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default='media/generic_img.png', null=True, upload_to='mediaCats/', verbose_name='תמונה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.CharField(blank=True, choices=[('Association', 'עמותה'), ('Foster', 'אומנה'), ('Adoption', 'אימוץ'), ('Pension', 'פנסיון')], default=None, max_length=20, null=True, verbose_name='מיקום'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='next_treatment',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='תאריך הטיפול הבא'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sterilization',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sterilization_approval',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mediaCats/', verbose_name='אישור סירוס/עיקור'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='ticks_fleas_treatment',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='טיפול קרציות ופרעושים'),
        ),
    ]
