# Generated by Django 4.0.4 on 2022-04-27 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0009_alter_cat_acceptance_date_alter_cat_death_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_ID', models.IntegerField(default=None, unique=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('ID_link', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='קישור לת"ז')),
                ('adopter_city', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='עיר מגורים')),
                ('adopter_street', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='רחוב')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='מספר טלפון')),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='כתובת מייל')),
                ('activity_status', models.CharField(choices=[('ACTIVE ADOPTION', 'אימץ'), ('RETURNED', 'החזיר')], default='אימץ', max_length=20, verbose_name='סטטוס פעילות')),
                ('black_listed', models.BooleanField(default=False, verbose_name='רשימה שחורה')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='death_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='תאריך הפטירה'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='death_reason',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='סיבת הפטירה'),
        ),
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(default=datetime.date.today, verbose_name='תאריך אימוץ')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.adopter', verbose_name='מאמץ')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.dog', verbose_name='כלב')),
            ],
        ),
        migrations.CreateModel(
            name='CatAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(default=datetime.date.today, verbose_name='תאריך אימוץ')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.adopter', verbose_name='מאמץ')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.cat', verbose_name='חתול')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='adopter_relation_cat',
            field=models.ManyToManyField(related_name='adoptions_cat', through='shelter.CatAdoption', to='shelter.adopter'),
        ),
        migrations.AddField(
            model_name='dog',
            name='adopter_relation_dog',
            field=models.ManyToManyField(related_name='adoptions_dog', through='shelter.DogAdoption', to='shelter.adopter'),
        ),
    ]
